// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilVerifyMobileOTPRequest is returned when the VerifyMobileOTPRequest is nil.
	ErrNilVerifyMobileOTPRequest = errors.New("input VerifyMobileOTPRequest is nil")

	// ErrVerifyMobileOTPRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrVerifyMobileOTPRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "VerifyMobileOTPRequest.RequestID", Type: "required"}

	// ErrVerifyMobileOTPRequestOTPCodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrVerifyMobileOTPRequestOTPCodeLengthValidation = govaliderrors.ValidationError{Reason: "field OTPCode length must be exactly 6", Path: "VerifyMobileOTPRequest.OTPCode", Type: "length"}

	// ErrVerifyMobileOTPRequestOTPCodeNumericValidation is the error returned when the field OTPCode is not numeric.
	ErrVerifyMobileOTPRequestOTPCodeNumericValidation = govaliderrors.ValidationError{Reason: "field OTPCode must be numeric", Path: "VerifyMobileOTPRequest.OTPCode", Type: "numeric"}

	// ErrVerifyMobileOTPRequestOTPCodeRequiredValidation is returned when the OTPCode is required but not provided.
	ErrVerifyMobileOTPRequestOTPCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field OTPCode is required", Path: "VerifyMobileOTPRequest.OTPCode", Type: "required"}

	// ErrVerifyMobileOTPRequestTxnIDRequiredValidation is returned when the TxnID is required but not provided.
	ErrVerifyMobileOTPRequestTxnIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TxnID is required", Path: "VerifyMobileOTPRequest.TxnID", Type: "required"}
)

func ValidateVerifyMobileOTPRequest(t *VerifyMobileOTPRequest) error {
	if t == nil {
		return ErrNilVerifyMobileOTPRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrVerifyMobileOTPRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.OTPCode) != 6 {
		err := ErrVerifyMobileOTPRequestOTPCodeLengthValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.OTPCode) {
		err := ErrVerifyMobileOTPRequestOTPCodeNumericValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.OTPCode == "" {
		err := ErrVerifyMobileOTPRequestOTPCodeRequiredValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.TxnID == "" {
		err := ErrVerifyMobileOTPRequestTxnIDRequiredValidation
		err.Value = t.TxnID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*VerifyMobileOTPRequest)(nil)

func (t *VerifyMobileOTPRequest) Validate() error {
	return ValidateVerifyMobileOTPRequest(t)
}
