// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilInitiateMobileChangeRequest is returned when the InitiateMobileChangeRequest is nil.
	ErrNilInitiateMobileChangeRequest = errors.New("input InitiateMobileChangeRequest is nil")

	// ErrInitiateMobileChangeRequestCustomerIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrInitiateMobileChangeRequestCustomerIDGTValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be greater than 0", Path: "InitiateMobileChangeRequest.CustomerID", Type: "gt"}

	// ErrInitiateMobileChangeRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrInitiateMobileChangeRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "InitiateMobileChangeRequest.CustomerID", Type: "required"}

	// ErrInitiateMobileChangeRequestNewMobileNumberLengthValidation is the error returned when the length of the field is not exactly 10.
	ErrInitiateMobileChangeRequestNewMobileNumberLengthValidation = govaliderrors.ValidationError{Reason: "field NewMobileNumber length must be exactly 10", Path: "InitiateMobileChangeRequest.NewMobileNumber", Type: "length"}

	// ErrInitiateMobileChangeRequestNewMobileNumberNumericValidation is the error returned when the field NewMobileNumber is not numeric.
	ErrInitiateMobileChangeRequestNewMobileNumberNumericValidation = govaliderrors.ValidationError{Reason: "field NewMobileNumber must be numeric", Path: "InitiateMobileChangeRequest.NewMobileNumber", Type: "numeric"}

	// ErrInitiateMobileChangeRequestNewMobileNumberRequiredValidation is returned when the NewMobileNumber is required but not provided.
	ErrInitiateMobileChangeRequestNewMobileNumberRequiredValidation = govaliderrors.ValidationError{Reason: "field NewMobileNumber is required", Path: "InitiateMobileChangeRequest.NewMobileNumber", Type: "required"}

	// ErrInitiateMobileChangeRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateMobileChangeRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of Portal Mobile PostOffice CallCenter AgentPortal", Path: "InitiateMobileChangeRequest.Channel", Type: "oneof"}

	// ErrInitiateMobileChangeRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrInitiateMobileChangeRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "InitiateMobileChangeRequest.Channel", Type: "required"}
)

func ValidateInitiateMobileChangeRequest(t *InitiateMobileChangeRequest) error {
	if t == nil {
		return ErrNilInitiateMobileChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.CustomerID > 0) {
		err := ErrInitiateMobileChangeRequestCustomerIDGTValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.CustomerID == 0 {
		err := ErrInitiateMobileChangeRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewMobileNumber) != 10 {
		err := ErrInitiateMobileChangeRequestNewMobileNumberLengthValidation
		err.Value = t.NewMobileNumber
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.NewMobileNumber) {
		err := ErrInitiateMobileChangeRequestNewMobileNumberNumericValidation
		err.Value = t.NewMobileNumber
		errs = append(errs, err)
	}

	if t.NewMobileNumber == "" {
		err := ErrInitiateMobileChangeRequestNewMobileNumberRequiredValidation
		err.Value = t.NewMobileNumber
		errs = append(errs, err)
	}

	if !(t.Channel == "Portal" || t.Channel == "Mobile" || t.Channel == "PostOffice" || t.Channel == "CallCenter" || t.Channel == "AgentPortal") {
		err := ErrInitiateMobileChangeRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrInitiateMobileChangeRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InitiateMobileChangeRequest)(nil)

func (t *InitiateMobileChangeRequest) Validate() error {
	return ValidateInitiateMobileChangeRequest(t)
}
