// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilVerifyEmailOTPRequest is returned when the VerifyEmailOTPRequest is nil.
	ErrNilVerifyEmailOTPRequest = errors.New("input VerifyEmailOTPRequest is nil")

	// ErrVerifyEmailOTPRequestRequestIDRequiredValidation is returned when the RequestID is required but not provided.
	ErrVerifyEmailOTPRequestRequestIDRequiredValidation = govaliderrors.ValidationError{Reason: "field RequestID is required", Path: "VerifyEmailOTPRequest.RequestID", Type: "required"}

	// ErrVerifyEmailOTPRequestOTPCodeLengthValidation is the error returned when the length of the field is not exactly 6.
	ErrVerifyEmailOTPRequestOTPCodeLengthValidation = govaliderrors.ValidationError{Reason: "field OTPCode length must be exactly 6", Path: "VerifyEmailOTPRequest.OTPCode", Type: "length"}

	// ErrVerifyEmailOTPRequestOTPCodeNumericValidation is the error returned when the field OTPCode is not numeric.
	ErrVerifyEmailOTPRequestOTPCodeNumericValidation = govaliderrors.ValidationError{Reason: "field OTPCode must be numeric", Path: "VerifyEmailOTPRequest.OTPCode", Type: "numeric"}

	// ErrVerifyEmailOTPRequestOTPCodeRequiredValidation is returned when the OTPCode is required but not provided.
	ErrVerifyEmailOTPRequestOTPCodeRequiredValidation = govaliderrors.ValidationError{Reason: "field OTPCode is required", Path: "VerifyEmailOTPRequest.OTPCode", Type: "required"}

	// ErrVerifyEmailOTPRequestTxnIDRequiredValidation is returned when the TxnID is required but not provided.
	ErrVerifyEmailOTPRequestTxnIDRequiredValidation = govaliderrors.ValidationError{Reason: "field TxnID is required", Path: "VerifyEmailOTPRequest.TxnID", Type: "required"}
)

func ValidateVerifyEmailOTPRequest(t *VerifyEmailOTPRequest) error {
	if t == nil {
		return ErrNilVerifyEmailOTPRequest
	}

	var errs govaliderrors.ValidationErrors

	if t.RequestID == "" {
		err := ErrVerifyEmailOTPRequestRequestIDRequiredValidation
		err.Value = t.RequestID
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.OTPCode) != 6 {
		err := ErrVerifyEmailOTPRequestOTPCodeLengthValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if !validationhelper.IsNumeric(t.OTPCode) {
		err := ErrVerifyEmailOTPRequestOTPCodeNumericValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.OTPCode == "" {
		err := ErrVerifyEmailOTPRequestOTPCodeRequiredValidation
		err.Value = t.OTPCode
		errs = append(errs, err)
	}

	if t.TxnID == "" {
		err := ErrVerifyEmailOTPRequestTxnIDRequiredValidation
		err.Value = t.TxnID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*VerifyEmailOTPRequest)(nil)

func (t *VerifyEmailOTPRequest) Validate() error {
	return ValidateVerifyEmailOTPRequest(t)
}
