// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	"unicode/utf8"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
	"gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/validationhelper"
)

var (
	// ErrNilInitiateEmailChangeRequest is returned when the InitiateEmailChangeRequest is nil.
	ErrNilInitiateEmailChangeRequest = errors.New("input InitiateEmailChangeRequest is nil")

	// ErrInitiateEmailChangeRequestCustomerIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrInitiateEmailChangeRequestCustomerIDGTValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be greater than 0", Path: "InitiateEmailChangeRequest.CustomerID", Type: "gt"}

	// ErrInitiateEmailChangeRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrInitiateEmailChangeRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "InitiateEmailChangeRequest.CustomerID", Type: "required"}

	// ErrInitiateEmailChangeRequestNewEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrInitiateEmailChangeRequestNewEmailEmailValidation = govaliderrors.ValidationError{Reason: "field NewEmail must be a valid email address", Path: "InitiateEmailChangeRequest.NewEmail", Type: "email"}

	// ErrInitiateEmailChangeRequestNewEmailMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 255.
	ErrInitiateEmailChangeRequestNewEmailMaxLengthValidation = govaliderrors.ValidationError{Reason: "field NewEmail must have a maximum length of 255", Path: "InitiateEmailChangeRequest.NewEmail", Type: "maxlength"}

	// ErrInitiateEmailChangeRequestNewEmailRequiredValidation is returned when the NewEmail is required but not provided.
	ErrInitiateEmailChangeRequestNewEmailRequiredValidation = govaliderrors.ValidationError{Reason: "field NewEmail is required", Path: "InitiateEmailChangeRequest.NewEmail", Type: "required"}

	// ErrInitiateEmailChangeRequestChannelOneofValidation is the error returned when the field is not one of the allowed values.
	ErrInitiateEmailChangeRequestChannelOneofValidation = govaliderrors.ValidationError{Reason: "field Channel must be one of Portal Mobile PostOffice CallCenter AgentPortal", Path: "InitiateEmailChangeRequest.Channel", Type: "oneof"}

	// ErrInitiateEmailChangeRequestChannelRequiredValidation is returned when the Channel is required but not provided.
	ErrInitiateEmailChangeRequestChannelRequiredValidation = govaliderrors.ValidationError{Reason: "field Channel is required", Path: "InitiateEmailChangeRequest.Channel", Type: "required"}
)

func ValidateInitiateEmailChangeRequest(t *InitiateEmailChangeRequest) error {
	if t == nil {
		return ErrNilInitiateEmailChangeRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.CustomerID > 0) {
		err := ErrInitiateEmailChangeRequestCustomerIDGTValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.CustomerID == 0 {
		err := ErrInitiateEmailChangeRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if !validationhelper.IsValidEmail(t.NewEmail) {
		err := ErrInitiateEmailChangeRequestNewEmailEmailValidation
		err.Value = t.NewEmail
		errs = append(errs, err)
	}

	if utf8.RuneCountInString(t.NewEmail) > 255 {
		err := ErrInitiateEmailChangeRequestNewEmailMaxLengthValidation
		err.Value = t.NewEmail
		errs = append(errs, err)
	}

	if t.NewEmail == "" {
		err := ErrInitiateEmailChangeRequestNewEmailRequiredValidation
		err.Value = t.NewEmail
		errs = append(errs, err)
	}

	if !(t.Channel == "Portal" || t.Channel == "Mobile" || t.Channel == "PostOffice" || t.Channel == "CallCenter" || t.Channel == "AgentPortal") {
		err := ErrInitiateEmailChangeRequestChannelOneofValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if t.Channel == "" {
		err := ErrInitiateEmailChangeRequestChannelRequiredValidation
		err.Value = t.Channel
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*InitiateEmailChangeRequest)(nil)

func (t *InitiateEmailChangeRequest) Validate() error {
	return ValidateInitiateEmailChangeRequest(t)
}
