// Code generated by govalid; DO NOT EDIT.
package handler

import (
	"errors"

	govalid "gitlab.cept.gov.in/it-2.0-common/n-api-validation"
	govaliderrors "gitlab.cept.gov.in/it-2.0-common/n-api-validation/validation/errors"
)

var (
	// ErrNilListCustomerRequestsRequest is returned when the ListCustomerRequestsRequest is nil.
	ErrNilListCustomerRequestsRequest = errors.New("input ListCustomerRequestsRequest is nil")

	// ErrListCustomerRequestsRequestCustomerIDGTValidation is the error returned when the value of the field is less than the 0.
	ErrListCustomerRequestsRequestCustomerIDGTValidation = govaliderrors.ValidationError{Reason: "field CustomerID must be greater than 0", Path: "ListCustomerRequestsRequest.CustomerID", Type: "gt"}

	// ErrListCustomerRequestsRequestCustomerIDRequiredValidation is returned when the CustomerID is required but not provided.
	ErrListCustomerRequestsRequestCustomerIDRequiredValidation = govaliderrors.ValidationError{Reason: "field CustomerID is required", Path: "ListCustomerRequestsRequest.CustomerID", Type: "required"}
)

func ValidateListCustomerRequestsRequest(t *ListCustomerRequestsRequest) error {
	if t == nil {
		return ErrNilListCustomerRequestsRequest
	}

	var errs govaliderrors.ValidationErrors

	if !(t.CustomerID > 0) {
		err := ErrListCustomerRequestsRequestCustomerIDGTValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if t.CustomerID == 0 {
		err := ErrListCustomerRequestsRequestCustomerIDRequiredValidation
		err.Value = t.CustomerID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*ListCustomerRequestsRequest)(nil)

func (t *ListCustomerRequestsRequest) Validate() error {
	return ValidateListCustomerRequestsRequest(t)
}
